require "rubygems"
require 'spec/rake/spectask'
 
desc "Run all specs"
Spec::Rake::SpecTask.new do |t|
  t.spec_files = FileList['spec/**/*_spec.rb']
  t.spec_opts = ['--options', 'spec/spec.opts']
end
 
Dir['tasks/**/*.rake'].each { |rake| load rake }